version: '2.1'
orbs:
  ostorlab-circleci: ostorlab-circleci/ostorlab@0.0.1
workflows:
  use-my-orb:
    jobs:
      - ostorlab-circleci/ostorlab:
          ostorlab_api_key: 6PEQ2wVG.otDRjvRbfdTPK2om7FuFpJLLOn66ssqo
          asset_type: android-apk
          break_on_risk_rating: HIGH
          max_wait_minutes: 5
          scan_profile: fast_scan
          scan_title: Test Circle CI workflow
          target: oxo_insecure.apk
          extra: 
